name: Test and Build Web

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_RPC_ENDPOINT: "https://api.devnet.solana.com"
